name: DevChat Electron CI
on:
  push:
    branches:
      - release

  workflow_dispatch:

env:
  REPO_ID: devchat-web-electron
  GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}

jobs:
  build-on-win:
    runs-on: windows-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies on submodule
        run: |
          cd devchat-web
          bun install
      - name: Build submodule
        run: |
          cd devchat-web
          set NODE_ENV electron
          bun run build:electron
      - name: Install dependencies
        run: bun install
      - name: Build & publish Electron app
        run: bun run publish
